#_*_ MakeFile _*_

default: compilation
	
	./P2

compilation:
	gcc -w   P2.c -o P2
	gcc -w   rm.c -o rm
	gcc -w   mkdir.c  -o mkdir
	gcc -w   ls.c  -o ls
	gcc -w   date.c  -o date
	gcc -w   cat.c  -o cat
